### ISSUE TITLE
Error instaling

### ISSUE THREAD

**Issue by LuisFSilva** [tpportugal/tpp#1]
Error while following installation guide.

When trying to clone:

> The authenticity of host 'github.com (192.30.253.112)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)?

> Warning: Permanently added 'github.com,192.30.253.112' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

> Please make sure you have the correct access rights
and the repository exists.

Solution:
Change URLs to subrepos to use HTTP instead of SSH.

I'll submit a PR soon.

**Comment by glaand** [comment]
Solved at https://github.com/glaand/tpp/commit/75e466c8c37f11006b601b38668e2a15e9c45204
