### ISSUE TITLE
Interação entre rotas

### ISSUE THREAD

**Issue by glaand** [tpportugal/tpp#17]
Para que possamos interagir entre rotas, isto é, caso o viajante tenha que mudar de linha para seguir viagem, vai ser necessário aplicar um algoritmo em que encontre a paragem mais próxima onde mudou de linha, isto tendo em conta o horário de transporte, duração de viagem e a disponibilidade do transporte. 

Para podermos fornecer as rotas mais rápidas até mesmo com várias mudanças de linhas, vai ser necessário aplicar investigação operacional para tirar melhor proveito dos dados.

Alguém tem alguma experiência neste ramo e que nos queira dar um input?

**Comment by VitorSantos1** [comment]
Nunca trabalhei na parte operacional; no entanto, posso lançar algumas situações que poderão levar a perceber o que determina uma mudança viável de rota:

* Coordenadas (estamos a falar da mesma paragem, geograficamente?)
* Condições da paragem (passagem coberta? acesso a pessoas de mobilidade reduzida?)
* Distância entre paragens (tempo que se demora de uma paragem para outra? Distância?)
* Tempos de espera entre mudanças de rota (o que é um tempo viável/realista de espera, entre rotas?)

Sem avançar para situações que não são prioridade, como por exemplo se usam o mesmo sistema de bilhética, penso que ajudaria levantar estas perguntas e saber com que variáveis, e com que precisão, podemos trabalhar.

**Comment by glaand** [comment]
A parte mais crucial do sistema vai ser a interpolação de estações. O objetivo final é que todas as rotas estejam interligadas num certo dia. Visto as rotas não serem constantes, isto é, mudarem diariamente, o cálculo das interpolações terá que ser diário. O princípio do cálculo das interpolações vai ser através de áreas circulares. Uma função matemática que encontre para x coordenada o y mais próximo, onde o y é a estação mais próxima. Após ter encontrado os pontos mais próximos, é preciso depois saber se para um certo horário haja algum transporte na coordenada y. Temos então dois fatores: A paragem mais próxima e o intervalo de compatibilidade de horários. Tendo isto interligado, podemos então concluir que todas as rotas de portugal estarão interligadas para uma certa hora. Não vejo que estas interpolações devam ser guardadas na base de dados pois o custo da manuntenção é demasiado elevado. Vejo isto sim num memory mapping como Elasticsearch. Agradecia que me desses inputs relativamente a esta questão.

**Comment by VitorSantos1** [comment]
A paragem mais próxima parece-me uma questão pacífica.

Sobre o intervalo de compatibilidade de horários, penso que seja variável em relação à viagem após o transbordo. Por exemplo, podes estar disponível para estar 20 minutos à espera de um expresso (aliás, essas transportadoras recomendam-te que estejas 15 minutos, antes da hora de partida), mas esses 20 minutos são demasiado tempo para fazer transbordo para uma transportadora urbana.

Por isso, para essa variável, teria em conta estas variáveis, passe a redundância:

* Distância da viagem após o transbordo;
* Tempo de espera da próxima viagem, caso o transbordo falhe para àquele horário. Neste caso, se tiveres um tempo de espera demasiado grande (imagina que perdes o último transporte das 00:00 e só voltas a ter às 06:00), o cálculo deve calcular a rota que ofereça garantias de que o utilizador não perde o último transporte.

Sobre o uso do ElasticSearch, concordo. No entanto, ele oferece gestão de filas de espera? Tens o RabbitMQ que implementa isso, mas nunca tive que o usar para nenhum projecto...

O que achas?

**Comment by Smamede** [comment]
Em que lingua e que voces pretendem codificar a app? Eu codifico em Ruby in Rails e ha gems que certamente antevem alguns dos problemas que voces podem estar a enfrentar. 

Acho que construir tudo do inicio pode ser extremamente dificil e nao optimiza o tempo. Porque que voces nao adaptam muitos dos metodos ja usados em outras aplicacoes similares a essa (usadas em outros paises), calculam certos aspectos que essa app precisa e depois alteram o CSS, Javascript e o HTML de acordo com o que voces pretendem?

Peco desculpas pelos erros autograficos (relacionados com acentos e c com cedilha); uso o teclado em ingles e este n possui estes elementos

**Comment by Rui-Santos** [comment]
@Smamede Estás no Slack do TPP? Podemos falar lá um bocado? Preciso de uma ajuda com RoR, se estiveres disposto a isso.
