### ISSUE TITLE
[QUESTION] RoadMap

### ISSUE THREAD

**Issue by Tiago-OP** [tpportugal/tpp#2]
Boas,

Acho a ideia interessante, e acho que devias implementar um roadmap na Wiki, para o pessoal que quer contribuir ter uma ideia do que é necessário fazer :)

Cumps,
TB

**Comment by fabiulous** [comment]
Concordo.

Eu posso ajudar a preparar uma versão básica da pagina (preferencialmente reactjs), mas seria melhor ter um roadmap.
Infelizmente não posso ajudar muito com python.

Abraço,
Fabio

**Comment by glaand** [comment]
Bem top a ideia. Acho que é a primeira coisa que vou fazer. Alguém da
subscribed list está interessado em ser o coordenador?

Am 07.02.2018 12:31 schrieb "Fabio Santos" <notifications@github.com>:

**Comment by Rui-Santos** [comment]
Eu concordo com reactjs para o frontend. Serve para web e mobile. O que evita andar a usar diferentes linguagens ou frameworks para o frontend.

**Comment by glaand** [comment]
@psyvisions @shizpi Conhecem a tecnologia **NativeScript** ?

**Comment by fabiulous** [comment]
NativeScript não.
Vou tentar ajudar o máximo que puder, mas tenho o Quero Emprego que me leva a maioria do tempo, portanto o que vou fazer mais e partilhar alguma da arquitetura que ja tenho feita, componentes e afins.

**Comment by glaand** [comment]
@Tiago-OP Roadmap: https://github.com/glaand/tpp/wiki/Roadmap
