### ISSUE TITLE
Fazer deployment, correndo apenas um script Bash

### ISSUE THREAD

**Issue by VitorSantos1** [tpportugal/tpp#20]
Como o próprio título diz, o objectivo é juntar as instruções de deployment da pilha Docker, num script em Bash. Isto é um bom avanço, pelos seguintes motivos:

* Instruções bastante mais fáceis para quem começa a colaborar, ficando com uma boa primeira impressão sobre o sistema e com um panorama geral da estrutura do sistema;
* Para quem já está cá há mais tempo, evita erros de digitação, que queimam sempre tempo e torna o desenvolvimento menos maçador.

**Comment by VitorSantos1** [comment]
Commits associados:

* https://github.com/glaand/tpp/commit/606dadb2fbf2d8f2248c0cc807513bdb4126ec01
* https://github.com/glaand/tpp/commit/66eb092806c2b40945aa0d02d0c1bc6478e0cc4b
* https://github.com/glaand/tpp/pull/22/commits/d35314e53f6e54de9a87298adbc1929668368f15

**Comment by VitorSantos1** [comment]
Pull request:

* https://github.com/glaand/tpp/pull/22

**Comment by glaand** [comment]
Merged
