### ISSUE TITLE
Medir a fiabilidade de cumprimento de horários

### ISSUE THREAD

**Issue by VitorSantos1** [tpportugal/tpp#21]
Como muita gente que usa transportes públicos, existem várias situações em que os transportes, ou chegam atrasados ou nem sequer aparecem. É uma situação crítica, mesmo para quem apanha apenas essa rota atrasada, que terá consequências maiores para quem queira mudar de rota.

Uma variável que pode ajudar a calcular a melhor rota, com o menor número de atrasos e supressões de viagem, seria ter duas variáveis: uma que indicasse que a rota chegou, com atrasos, e outra que indicasse a supressão da viagem.

Com isto, também teremos a classificação da companhia, factor importante de desempate de rotas que tenham paragens coincidentes.

**Comment by iursevla** [comment]
Parece-me bem.

Em alguns casos se a companhia disponibilizar uma API para acedermos aos horários em tempo real poderia também ser uma factor preferencial para este cálculo. 
É certo que para algumas companhias seria muito complicado fazer isto, enquanto que para outras seria super simples.

**Comment by VitorSantos1** [comment]
Ou também, futuramente, seria uma forma do passageiro indicar se tal horário é cumprido ou não, ao estilo do Waze. 🙂 

A ideia é haver várias partes a policiarem-se umas às outras, de forma a que o cálculo da rota seja o mais previsível possível.
