### ISSUE TITLE
Como submeter mais localidades?

### ISSUE THREAD

**Issue by Rui-Santos** [tpportugal/tpp#3]
OK, Instalei o API e corri-o, tudo funcional. Mas só tem Distritos e Cidades, penso eu. Como se pode contribuir com mais dados, tipo concelhos, freguesias, vilas, localidades/aldeias?

Eu há uns uns anos fui obrigado a arranjar uma lista de concelhos e freguesias, e foi fácil, pois penso que foi no site da ANMP(Associação Nacional de Municípios de Portugal), que a encontrei. As localidades com sorte também se arranjarão nesse mesmo site, ou noutro qualquer site governamental, tipo nos sites das câmaras municipais. Penso que todos os que já visitei, que não foram muitos, tinham uma lista das localidades do concelho por lá.

Qual o formato em que os dados deverão estar? Um ficheiro de texto por cada categoria, com 1 entrada por linha será suficiente? Se for, posso começar já a tratar disso.

**Comment by fabiulous** [comment]
Podem ir buscar os distritos e concelhos ao Queroemprego:

https://api.queroemprego.pt/graphql?query=query%7B%0A%20%20locations%20%7B%0A%20%20%20%20id%2C%0A%20%20%20%20name%2C%0A%20%20%20%20children%20%7B%0A%20%20%20%20%20%20id%2C%0A%20%20%20%20%20%20name%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D

**Comment by fabiulous** [comment]
Associamos as localidades através de um parentId da mesma tabela que pode ou não ser null

**Comment by glaand** [comment]
Nice pelo running!
As localidades/aldeias são ser definidas pelo modelo: stations
Os concelhos são definidos pelo modelo: communities.

Começa com os concelhos. Top seria que convertesses a lista para SQL e assim integrávamos nas migrações do projeto.

**Comment by glaand** [comment]
![image](https://user-images.githubusercontent.com/17197309/35933916-557d07f8-0c3c-11e8-938a-b9616e767d5c.png)
City é uma ForeignKey ao modelo cities.

**Comment by Rui-Santos** [comment]
Dás-me um exemplo da estrutura que deverei criar? Tipo um exemplo com dados reais. Usa um Concelho e uma localidade qualquer te venha à cabeça. Eu sou bom a imitar, mas não sou grande programador, e bases de dados não são mesmo algo de que perceba muito, mas penso que seja só repetir o exemplo para cada entrada =D

**Comment by fabiulous** [comment]
Huum, não sei se faz sentido ter stations como o modelo para uma aldeia, visto que uma aldeia é uma localidade que tem um parente.

As estações são data points com diferentes tipos BUS, METRO, TRAM. Cada data point pode ter um ou mais tipos, porque em estações de metro tens também autocarros.
Nas cidades maiores pelo menos.

De momento apenas precisas de 2 modelos: locations e stations
Location 1:N Location
Location 1:N Stations

**Comment by glaand** [comment]
@psyvisions, Se fores ao ficheiro: `api/apps/cities/migrations/0001_initial.py` tens lá o dump das cidades em SQL, baseia-te nisso
'cascais' -> O slug do concelho  
'Cascais' -> O nome do concelho
'lisboa' -> O slug da cidade
`migrations.RunSQL(
            "INSERT INTO {0}_community (slug, name, city) SELECT 'cascais' as slug, 'Cascais' as name, city.id FROM cities_city as city WHERE city.slug = 'lisboa';".format(
                'communities')),`

**Comment by glaand** [comment]
@shizpi ou seja criar um modelo só para as freguesias então?

**Comment by fabiulous** [comment]
@glaand nepia, distrito, concelho ou freguesia é tudo o mesmo, uma localidade onde apenas algumas são children de outras. Corrige-me se me estiver a falhar algo.

**Comment by Rui-Santos** [comment]
Devemos distinguir entre Cidades, Vilas e Localidades? Porque se não, então Cities deverá passar a ser Localities, não? E uma Locality será children de um District, County e Parish(Distrito, Concelho e Freguesia) Mas depois, vilas e cidades têm várias freguesias... hmmm


Estruturas de bases de dados são lixadas e partem-me a cabeça toda.

**Comment by glaand** [comment]
@psyvisions Podes na mesma continuar com a resolução deste problema que entretanto vou definir a base de dados na Roadmap

**Comment by Rui-Santos** [comment]
Vou tentar usar algo assim, só para ter uma estrutura, ao recolher os dados, depois então se adapta à base de dados.

```
Distrito1
	Concelho1
		Freguesia1
			Localidade1
			Localidade2
		Freguesia2
			Localidade1
			Localidade2
	Concelho2
		Freguesia1
			Localidade1
			Localidade2
		Freguesia2
			Localidade1
			Localidade2
Distrito2
	Concelho1
		Freguesia1
			Localidade1
			Localidade2
		Freguesia2
			Localidade1
			Localidade2
	Concelho2
		Freguesia1
			Localidade1
			Localidade2
		Freguesia2
			Localidade1
			Localidade2
```

**Comment by glaand** [comment]
Ok! Ou seja, o modelo cidade deverá ser renomeado para concelho?

**Comment by Rui-Santos** [comment]
Possívelmente. Afinal os Concelhos são todos cidades ou vilas, eu nem reparei se tens vilas incluídas no teu modelo cidade, strike that, não tens, já fui verificar. Tenta ter uma ideia da organização pelo sítio onde estou a ir buscar os dados iniciais, que não incluem localidades, apenas Distritos, Concelhos/Municípios, e Freguesias 

http://www.anmp.pt/anmp/pro/mun1/mun205w1.php?dis=01&Itemid=128

As Localidades depois vão dar mais trabalho. Serão milhares delas, claro que nem todas terão transportes para lá, mas isso também só saberemos depois de começarmos a inserir percursos e horários, não é?

**Comment by glaand** [comment]
Certo, convém ter todos os dados presentes. Como o @shizpi disse e muito bem, numa localidade pode haver várias estações e de vários tipos (Metro, Autocarro, Comboio). Vamos começar então primeiro pela obtenção dos dados das regiões.

**Comment by Rui-Santos** [comment]
É isso. Depois então se decidirá a melhor maneira de estrutar a base de dados. Slow and steady wins the race.
Possivelmente amanhã a lista sem as localidades está pronta. 
As localidades depois vão-me obrigar a visitar os cerca de 450 sites dos municípios, um a um, e aí os dados já não estarão tão bem formatados como estes. Mas nós também não temos pressa. Isto é um projeto com uma dimensão considerável, afinal. E enquanto eu faço isso, vocês programadores a sério, concerteza terão muito trabalho para fazer.

**Comment by jrocharodrigues** [comment]
@psyvisions Penso que aqui http://centraldedados.pt/codigos_postais/ deves ter a informação toda que precisas (distritos, concelhos, localidades) já estruturada.
Mesmo que não esteja com a estrutura que pretendes, deve ser mais fácil tirar daqui do que retirar dos sites dos municípios.

**Comment by glaand** [comment]
@jrocharodrigues e tem formato CSV e JSON!! Que espetáculo!

**Comment by Rui-Santos** [comment]
@jrocharodrigues estava mesmo no google a procurar uma lista em csv, já me poupaste o trabalho lol Muito obrigado!

**Comment by Rui-Santos** [comment]
@glaand e está no github também http://github.com/centraldedados/codigos_postais/

**Comment by glaand** [comment]
@psyvisions Faz o seguinte então! 
 - Fork do TPP
 - Git pull do repo original
 - Faz git clone do projeto https://github.com/centraldedados/codigos_postais/ para dentro deste diretorio: api/vendors/centraldedados/codigos_postais
 - git commit & git push para o teu fork
 - Faz um pull request

Tudo feito posso fazer merge das tuas alterações. Isto serve para que as tuas contribuições sejam notáveis no git.

Se precisares de ajuda entra no Slack: https://goo.gl/nYWD14

Abraços
