### ISSUE TITLE
Executar "set_development.sh"  retorna - "ERROR 'Couldn't find env file'"

### ISSUE THREAD

**Issue by OldMetalmind** [tpportugal/tpp#31]
- Depois de fazer clone com sucesso 
`git clone --recurse-submodules https://github.com/glaand/tpp.git`

- Entrei na pasta 'tpp' criada e executei script _set_development.sh_ 
```
$ bash set_development.sh 
docker-compose version 1.20.1, build 5d8c71b
ERROR: Couldn't find env file: (...)/tpp/.env/development.env
```

- Decidi criar esse ficheiro vazio, realizou o pull dos docker imagens e mas depois termina com o erro  
```
$ bash set_development.sh 
(...)
docker-compose version 1.20.1, build 5d8c71b
(File "/code/api/settings.py", line 5, in <module>
    SECRET_KEY = os.environ['DJANGO_SECRET_KEY']
  File "/usr/local/lib/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: DJANGO_SECRET_KEY

```

Nota: Eu defini uma variável de sistema _DJANGO_SECRET_KEY="inventado"_ julgando que era usado só para desenvolvimento local mas mesmo assim não deu.

[log.txt - depois de criar o ficheiro development.env vazio](https://github.com/glaand/tpp/files/1860154/log.txt)

**Comment by glaand** [comment]
Criei ficheiros .env por default para poder initializar o projeto. Basicamente o .env depende do ambiente de execução do projeto. Foi resolvido neste commit --> d9815cca93b43fc37593c3735161ec61d36c54b1
