### ISSUE TITLE
Accesso

### ISSUE THREAD

**Issue by OldMetalmind** [tpportugal/tpp#32]
Em Dev, depois de inicializar o projecto com sucesso.

Ao abrir a "Visão geral da API" ( http://0.0.0.0:8000 ) ou "API em formato de JSON" ( http://0.0.0.0:8000/?format=json ) pede-me para autenticar.

<img width="472" alt="screen shot 2018-03-30 at 15 45 42" src="https://user-images.githubusercontent.com/404874/38143378-2442a8ea-3438-11e8-9257-30310ca9a5fa.png">

Não encontrei forma a criar novos usarios em dev.

**Comment by glaand** [comment]
Cria um utilizador superuser com o seguinte comando:  
 `docker-compose -f docker-compose.development.yml run --rm web python manage.py createsuperuser` . 
Acho que não é necessário criar um utilizador default pois o django fornece um comando para criar superusers, o que acham?

**Comment by OldMetalmind** [comment]
Concordo que não haja necessidade utilizador default mas no entanto acho fulcral que tal seja informado e explicado, para facilitar a contribuição.

**Comment by glaand** [comment]
@OldMetalmind Com certeza! Realmente é algo que não está explicito. Gostarías de completar o README.md com os passos necessários para criar um super-utilizador?

**Comment by OldMetalmind** [comment]
@glaand já fiz um PR #33
