### ISSUE TITLE
Lista de todos os tipos de transporte

### ISSUE THREAD

**Issue by glaand** [tpportugal/tpp#5]
É necessário definir a lista de todos os tipos de transporte em portugal (incluíndo as regiões autónomas).

A lista pode ser entregue nos seguintes formatos:
CSV
TSV
JSON

**Comment by glaand** [comment]
Assigned: @shizpi

**Comment by fabiulous** [comment]
BUS, METRO, TRAM, INTERCITY_BUS, TRAIN, FERRIE, PLANE

Nao tenho certeza de devemos distinguir BUS e INTERCITY_BUS

**Comment by glaand** [comment]
LOCAL_BUS e INTERCITY_BUS talvez?

**Comment by fabiulous** [comment]
Aqui ha city trains e intercity trains. Acredito que hajam tambem em Lisboa, nao?

**Comment by glaand** [comment]
Isso só vai gerar complicações, é melhor deixar só BUS para todos

**Comment by fabiulous** [comment]
E apenas um enum ou uma row numa tabela.
Se for preciso distingir tambem se faz.
E melhor nao fazer overengineering agora

**Comment by PedroACaldeira** [comment]
hey! Mal soube deste projeto resolvi arranjar conta no git e pôr mãos à obra. Sou estudante de Engenharia Informática e estou interessado em dar uma mãozinha neste projeto! Contem comigo para angariar todos os horários dos transportes da zona de Setúbal!

**Comment by glaand** [comment]
done!
