### ISSUE TITLE
Definir a estrutura da base de dados (Diagrama Modelo ER)

### ISSUE THREAD

**Issue by glaand** [tpportugal/tpp#6]
Link do diagrama: https://goo.gl/knyWEZ

Pessoal agradecia o vosso input.

Caso queiram contribuir no diagrama, apenas têm que abrir o link, fazer as alterações e depois ao guardar, autorizar o draw.io no github e escolher o fork do tpp para fazer commit. Depois façam pull request para fazermos peer review!

**Comment by glaand** [comment]
Assigned to: @Qu4tro

**Comment by PedroACaldeira** [comment]
Hey hey 
Estava aqui a pensar e se calhar até podia ser interessante se houvesse uma associação entre "Localidades" e "Localidades" que podia exprimir o transporte existente entre duas localidades.

**Comment by glaand** [comment]
@PedroACaldeira Entra no nosso Slack para discutirmos a ideia :)

**Comment by glaand** [comment]
Linking issues: https://github.com/glaand/tpp/issues/8

**Comment by VitorSantos1** [comment]
Com os dados GTFS que temos, descobri um importador que permite importá-los para tabelas no PostgreSQL: https://cbick.github.io/gtfs_SQL_importer/html/index.html

Penso que, usando o diagrama na issue #8, talvez ligando o "places" a "stops" conseguimos ter uma relação entre rotas e locais. :)

**Comment by glaand** [comment]
Assigned to: @glaand

**Comment by glaand** [comment]
Esboço do modelo ER finalizado, precisa-se de 4 reviewers:

- @psyvisions 
- @VitorSantos1 
- @jorgeraujo 
- @Qu4tro

![image](https://user-images.githubusercontent.com/17197309/36082434-a4cafd2c-0fa9-11e8-8efe-80cd448ebbcf.png)

**Comment by Tiago-OP** [comment]
Na minha opinião parece-me um pouco confuso, ou posso não estar a perceber bem o fim de cada tabela.

Mas por exemplo, já que tens distrito e cidade, estas tabelas não deveriam estar ligadas às rotas?
Ok talvez já esteja a perceber,

Cidades tem x paragens(adicionava FKeys das cidades na tabela)
Cada Rota tem x paragens(aqui talvez um ID sequencial por ordem de paragem com fkey para a tabela paragens)
Cada Rota também tem x trips (cada viagem tem o seu horário)

Stopline é o horário de cada paragem da rota? Porque não alterar a tabela rotas para por exemplo:

1 - Lisboa (a primeira é a origem) -> fkey horario (tempo de arranque)
2 - Aveiro (segunda paragem da rota) -> fkey horario (tempo de chegada e tempo de arranqe)
3 -> Porto (ultima entrada na tabela, destino) -> fkey horario de chegada 

Talvez em vez de ter uma tabela horário adicionar dois campos à tabela rota com time stamp (hh::mm:ss).

Na tabela trips ficavas apenas com o id para rotas e um time tb (yy-mm-dd) e com id das agencias
ex:
routeID : 1 ^^
Date; 2018-02-08
Agency: xx

routeID : 2 ^^
Date; 2018-02-09
Agency: xx


Tabela serviços e calendar date, eu tirava pois a informação pode ser adicionada nas outras, o que torna a coisa bem mais simples.

Não sou nenhum expert em BDs mas sou grande apologista da simplicidade, no entanto espera por mais opiniões!

**Comment by Rui-Santos** [comment]
@Tiago-OP O esquema está a espelhar o formato GTFS, mais ou menos, pois ainda faltam alguns campos. Pode ver a aqui a [especificação do formato GTFS](https://developers.google.com/transit/gtfs/reference/)
Provavelmente isto é o menos confuso que pode ficar por agora. Pode ver aqui um [exemplo de um ficheiro GTFS](http://www.transporlis.pt/Portals/0/OpenData/gtfs/zip/1/gtfs_1.zip) que será utilizado para inserir os dados na DB.
Mesmo os dados que que não estão em GTFS, espelham mais ou menos essa estrutura. 

E sim, também a tabela Stops precisará de uma FKey city mas para isso precisaremos de trabalhar em algo para conseguir essa informação quer seja utilizando a fórmula de Haverstein sugerida pelo @glaand ou usando geo localização reversa. na altura de inserir os dados na DB.

**Comment by Tiago-OP** [comment]
Ah ok, peço desculpa então :), mais logo já dou uma vista de olhos nessa documentação! GJ

**Comment by Rui-Santos** [comment]
> Não sou nenhum expert em BDs... ....no entanto espera por mais opiniões!

Já somos dois, mas eu ainda percebo menos de DB's ;) Também pouco mais posso contribuir que com opiniões. E não tem que pedir desculpa de nada, ora essa. Aliás, agradecemos as suas opiniões.

Agora mudando de assunto, para espelhar melhor os dados que temos vindos do vendor/centraldedados/códigos_postais, sugiro este esquema, com a tabela City/Localidades a ser povoada através dos dados de geolocalização das Stops/Paragens, ou dos códigos postais em conjunto com geolocalização reversa das Stops/Paragens. Penso que isso simplificaria a busca, pois um utilizador web, assim que introduzisse uma Localidade na caixa de pesquisa, o serviço poderia logo retornar uma lista de paragens nessa localidade, ordenadas por distância ascendente do utilizador, se a isso tivermos acesso, com o tipo de meio de transporte e o nome da Operadora/Agency, talvez apresentados como ícones. Esta parte da apresentação já seria para o frontend, só escrevi mesmo para não me esquecer. 
![modelo_er](https://user-images.githubusercontent.com/471766/36108826-a263a41e-1015-11e8-87cc-6c9150b2eec1.png)

**Comment by jorgeraujo** [comment]
Vou ter uma reunião esta quinta para receber algum feedback de um professor que percebe de bd's. Vai ser uma espécie de validação, por isso era porreiro darem todo o input que conseguirem até lá!

**Comment by VitorSantos1** [comment]
@psyvisions @jorgeraujo Não tenho nada a apontar a este último diagrama. Dos casos que me lembro que podem ser menos claros, iremos ter sempre ids em todas as instâncias - o que resolve casos em que as linhas têm números iguais mas rotas diferentes, dependendo das alturas do dia.

Para testar a força da estrutura, é encaixá-la, tal como está, em companhias que sejam mais flexíveis na forma como dão nomes às linhas. Na que me estou a basear (Espírito Santo), esta estrutura é resiliente. :)

O que acho que pode ajudar a mostrar é organizar esse diagrama numa estrutura em árvore, com a `Stoptime` como raiz. Desta forma:

```
Stoptime
| Trip
| - Route
| - Calendar Date
| -- Service
| Stop
| - City
| -- County
| --- District
```

**Comment by t1ag0x** [comment]
Podem também incluir o campo localização nas paragens/estações, com as coordenadas GPS, sempre dá para fazer mapas bonitos...
EDIT: já vi o 'lat' e o 'lon'

**Comment by glaand** [comment]
![graph](https://user-images.githubusercontent.com/17197309/36333150-88abe5a0-1375-11e8-8f94-7bd484235489.png)
Diagrama atual até não houver mudanças
