### ISSUE TITLE
Wiki not editable?

### ISSUE THREAD

**Issue by waldyrious** [tpportugal/tpp#62]
I might be missing something, but upon visiting the page [https://github.com/tpportugal/tpp/wiki/TPP---Conceito](https://github.com/tpportugal/tpp/wiki/TPP:-Conceito), I cannot see the edit button. I thought wikis on github were always editable by any user of the site. Is there a specific configuration that you have toggled to make it otherwise?

**Comment by Rui-Santos** [comment]
I think the default for Github wiki pages is to restrict editing to users with push access to the repository.

**Comment by waldyrious** [comment]
Oh, they swapped their policy on this, I see. [It used to be](http://web.archive.org/web/20150814132703/https://help.github.com/articles/about-github-wikis/) that the default is every user could edit, and restricting that was an opt-in setting.
> By default, every user can make changes to public wikis, but you can configure this to be enabled only for collaborators on your repository.

[Now](https://help.github.com/articles/about-github-wikis/) it's the opposite:

> By default, only collaborators on your repository can make changes to wikis, but you can configure this to be enabled for all users on public repositories.

In any case, I'd suggest [changing that setting](https://help.github.com/articles/changing-access-permissions-for-wikis/), as that encourages participation by providing a low-barrier way to start contributing.

**Comment by glaand** [comment]
@waldyrious changed!
