### ISSUE TITLE
Usar dados GTFS?

### ISSUE THREAD

**Issue by glaand** [tpportugal/tpp#8]
Usar dados GTFS?

**Comment by Rui-Santos** [comment]
Podes começar por aqui http://dadosabertos.cm-lisboa.pt/organization/transporlis

E era uma boa ideia, se conseguíssemos converter os horários em GTFS, acho que o problema principal serão os dados de posicionamento GPS, que não existem, e estarmos nós a tentar localizar as paragens é trabalho impossível. Só mesmo indo lá, e trabalho de campo, por enquanto, é para esquecer

**Comment by glaand** [comment]
Como a maior parte da opendata encontra-se disponível em formato GTFS, o best-case é mesmo defini-lo como requisito. Caso seja necessário digitalização de dados, o formato também terá que corresponder a GTFS.

Diagrama GTFS:

![image](https://user-images.githubusercontent.com/17197309/36043620-2fe1c49e-0dd0-11e8-80ec-5a84737ae380.png)

**Comment by iursevla** [comment]
@psyvisions  @glaand para as localizações GPS de cada estação, seja de autocarro/metro/comboio/etc podemos usar o OpenStreetMap. 
Mas claro teremos de ser nós a fazer parsing de todo o ficheiro. 
Não tenho muito tempo mas posso tentar fazer um pequeno script para um ficheiro local (por exemplo Almada) e depois vemos se faz sentido ou não.

**Comment by Rui-Santos** [comment]
@iursevla penso que uma grande parte, se não mesmo a maioria, dos dados que já temos têm coordenadas GPS para estações/apeadeiros de comboios e paragens de autocarro. Apenas iremos precisar dos dados em falta, e para esses sim, usar os dados do OSM será o ideal.
